baseURL = 'https://example.com'

languageCode = 'en'
title = 'Hugo Anya'
theme = "hugo-anya"

paginate = 10

disqusShortname = "https-hugo-anya-netlify-app"

enableRobotsTXT = true

[params]
  
  # # You can use an emoji as the site logo:
  # titleEmoji  = "💊"

  # # Or specify the path to the image, relative to the /main_dir/static directory:
  # titleLogo = "/icons/favicon.svg"
  # Or change and use the svg logo located in /main_dir/themes/hugo-anya/assets/icons/logo.svg (In this case, the color of the logo may change depending on the light/dark theme).
  useLogoPartialSVG = true

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  mainSections = ['post']

  siteName = "Hugo Anya is Amazing"
  siteDesc = "Hugo is Absurdly Fast!"
  author = "Limbend"

  [params.colorScheme]
    # Enable toggle colorScheme
    # Default to true
    toggle = true
    # Default colorScheme
    # Default to auto
    # default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    # dev-to = ""
    # email = ""
    # facebook = ""
    # github = ""
    # instagram = ""
    # linkedin = ""
    # medium = ""
    # stack-overflow = ""
    # steam = ""
    # telegram = ""
    # twitter = ""
    # twitch = ""
    # whatsapp = ""

[menu]
[[menu.header]]
  name = "Posts"
  url = "/posts/"
  weight = 1
[[menu.header]]
  name = "Features"
  url = "/themefeatures/"
  weight = 2
[[menu.footer]]
    name = "RSS"
    url = "/index.xml"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ['HTML', 'RSS']

[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1